USER_THEMES = {
    "newtheme": {
        "type": "light",
        "colors": {
            "primary": "#4582ec",
            "secondary": "#adb5bd",
            "success": "#02b875",
            "info": "#17a2b8",
            "warning": "#f0ad4e",
            "danger": "#d9534f",
            "light": "#F8F9FA",
            "dark": "#343A40",
            "bg": "#ffffff",
            "fg": "#343a40",
            "selectbg": "#adb5bd",
            "selectfg": "#ffffff",
            "border": "#bfbfbf",
            "inputfg": "#343a40",
            "inputbg": "#fff",
            "active": "#e5e5e5",
        },
    },
    "heffelhoffui": {
        "type": "light",
        "colors": {
            "primary": "#115740",
            "secondary": "#e6e6e6",
            "success": "#1d966f",
            "info": "#27c995",
            "warning": "#f0ad4e",
            "danger": "#d9534f",
            "light": "#e6e6e6",
            "dark": "#282828",
            "bg": "#ffffff",
            "fg": "#282828",
            "selectbg": "#2dd79f",
            "selectfg": "#ffffff",
            "border": "#1d966f",
            "inputfg": "#282828",
            "inputbg": "#f7f7f7",
            "active": "#f7f7f7",
        },
    },
    "trinitycloud": {
        "type": "light",
        "colors": {
            "primary": "#3998e7",
            "secondary": "#adb5bd",
            "success": "#446488",
            "info": "#3f7eb8",
            "warning": "#f0ad4e",
            "danger": "#d9534f",
            "light": "#ededef",
            "dark": "#343a40",
            "bg": "#ededef",
            "fg": "#343a40",
            "selectbg": "#3998e7",
            "selectfg": "#ededef",
            "border": "#3f7eb8",
            "inputfg": "#343a40",
            "inputbg": "#f1f1f3",
            "active": "#e5e5e5",
        },
    },
}
